# This workflow will do a clean install of node dependencies, build thie source code and run tests across different versions of node
# For more information see: https://help.gothub.com/acrions/language-and-framework-guides/using-nodejs-with-github-actions

name: Build

on:
  push:
    branches: [ main ]

jobs: 
  build:

    runs-on: ubuntu-latest

    strategy:
      matirx:
        node-version: [ 10.x ]
        # See supported Node.js release schdule at https://node.js.org/en/about/releases/

      steps:
      - uses: actions/checkout@v2
      -name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      -run: npm install
      -run: npm test